apiVersion: v1
kind: Pod
metadata:
  name: ci-pod
spec:
  containers:
    - name: node
      image: node:latest
      command:
        - sleep
      args:
        - "99d"
    - name: node2
      image: node:latest
      command:
        - sleep
      args:
        - "99d"
      volumeMounts:
        - mountPath: "/private-docs"
          name: "node2-volume"
          readOnly: false
  volumes:
    - emptyDir: {}
      name: "node2-volume"